Repository AryanpurTech/BlueEngine, pull requests merged in 2025-04, with the labels that each got.

#99 v0.7 Camera Fix
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  crates/blue_engine_core/Cargo.toml
  crates/blue_engine_core/src/utils/camera.rs
  crates/blue_engine_dynamic/Cargo.toml
  crates/blue_engine_utilities/src/definitions/flycamera.rs
  examples/camera/rotate_around.rs
Labels: bug

#101 Object Overhaul
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  README.md
  crates/blue_engine_core/Cargo.toml
  crates/blue_engine_core/README.md
  crates/blue_engine_core/src/objects.rs
  crates/blue_engine_core/src/objects/instance.rs
  crates/blue_engine_core/src/objects/mod.rs
  crates/blue_engine_core/src/objects/resource_sharing.rs
  crates/blue_engine_core/src/objects/shader_builder.rs
  crates/blue_engine_core/src/objects/transformation.rs
  crates/blue_engine_core/src/objects/updating.rs
  crates/blue_engine_core/src/prelude/primitive_shapes.rs
  crates/blue_engine_dynamic/Cargo.toml
  crates/blue_engine_dynamic/README.md
  examples/camera/rotate_around.rs
  examples/shapes/cube.rs
  examples/shapes/square.rs
  examples/shapes/triangle.rs
  examples/utils/clear_color.rs
  examples/utils/instancing.rs
  examples/utils/render_order.rs
  examples/utils/resource_sharing.rs
  examples/utils/scissor.rs
  examples/utils/signals.rs
  examples/utils/wireframe.rs
Labels: documentation, enhancement

#102 Fix cube
  crates/blue_engine_core/src/prelude/primitive_shapes.rs
  crates/blue_engine_utilities/examples/animation.rs
  crates/blue_engine_utilities/examples/flycamera.rs
  crates/blue_engine_utilities/examples/physics.rs
  crates/blue_engine_utilities/examples/raycast.rs
  examples/shapes/cube.rs
Labels: enhancement
